const app = document.querySelector('#app');
const today = new Date();
const monthFormatter = new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric' });
const dateFormatter = new Intl.DateTimeFormat('en-IN', { month: 'long', day: 'numeric', year: 'numeric' });
const monthKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const parseDate = (key) => { const [year, month, day] = key.split('-').map(Number); return new Date(year, month - 1, day); };
const sameDay = (a, b) => dateKey(a) === dateKey(b);
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const litres = (value) => `${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 2 })} L`;

const defaults = { price: 60, quantities: [0.5, 1, 1.25, 1.5, 1.75, 2, 2.5] };
let settings = JSON.parse(localStorage.getItem('milk-settings') || 'null') || defaults;
let records = JSON.parse(localStorage.getItem('milk-records') || '{}');
let currentView = 'today';
let visibleMonth = new Date(today.getFullYear(), today.getMonth(), 1);
let selectedDate = new Date(today);
let toastTimer;
let undoAction;
let supabaseClient;
let cloudUser;
let activeFamily;
let authMode = 'login';
let pendingSync = JSON.parse(localStorage.getItem('milk-pending-sync') || '[]');
const cloudConfigured = Boolean(window.SUPABASE_CONFIG?.url?.startsWith('http') && window.SUPABASE_CONFIG?.publishableKey && !window.SUPABASE_CONFIG.publishableKey.includes('YOUR_'));
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
const isFutureKey = key => key > dateKey(today);
function setSyncStatus(label, offline = false) { const status = document.querySelector('#sync-status'); if (status) { status.textContent = label; status.classList.toggle('offline', offline); } }
function cloudReady() { return Boolean(supabaseClient && cloudUser && activeFamily); }
async function cloudPull() { if (!cloudReady()) return; setSyncStatus('Syncing'); const { data, error } = await supabaseClient.from('milk_records').select('date, quantity_litres, price_per_litre, note, updated_at').eq('family_id', activeFamily.id); if (error) throw error; records = Object.fromEntries((data || []).map(item => [item.date, { quantity: Number(item.quantity_litres), price: Number(item.price_per_litre), note: item.note || '', updatedAt: item.updated_at }])); const { data: familySettings } = await supabaseClient.from('family_settings').select('default_price, quick_quantities').eq('family_id', activeFamily.id).maybeSingle(); if (familySettings) { settings = { price: Number(familySettings.default_price), quantities: familySettings.quick_quantities || defaults.quantities }; } saveData(); setSyncStatus('☁ Synced'); }
async function cloudSaveRecord(key) { if (!cloudReady()) return; const record = records[key]; const { error } = await supabaseClient.from('milk_records').upsert({ family_id: activeFamily.id, date: key, quantity_litres: record.quantity, price_per_litre: record.price, note: record.note || '', created_by: cloudUser.id, updated_at: new Date().toISOString() }, { onConflict: 'family_id,date' }); if (error) throw error; setSyncStatus('☁ Synced'); }
async function cloudDeleteRecord(key) { if (!cloudReady()) return; const { error } = await supabaseClient.from('milk_records').delete().eq('family_id', activeFamily.id).eq('date', key); if (error) throw error; }
function queueSync(key, deleted = false) { pendingSync = [...pendingSync.filter(item => item.key !== key), { key, deleted }]; localStorage.setItem('milk-pending-sync', JSON.stringify(pendingSync)); setSyncStatus('⚠ Offline', true); }
async function flushPending() { if (!cloudReady() || !pendingSync.length) return; const queue = [...pendingSync]; for (const item of queue) { if (item.deleted) await cloudDeleteRecord(item.key); else await cloudSaveRecord(item.key); pendingSync = pendingSync.filter(entry => entry.key !== item.key); } localStorage.setItem('milk-pending-sync', JSON.stringify(pendingSync)); }
function cloudError(error) { console.error(error); setSyncStatus('⚠ Offline', true); showToast('Something went wrong. Please try again.'); }
function renderAuth(message = '') { const signUp = authMode === 'signup'; document.querySelector('.bottom-nav').style.display = 'none'; document.querySelector('#settings-button').style.display = 'none'; app.innerHTML = `<section class="auth-view"><div class="auth-mark">🥛</div><p class="eyebrow">Daily Milk Tracker</p><h1>${signUp ? 'Create your account' : 'Welcome back'}</h1><p class="subtitle">${signUp ? 'Start a shared family milk calendar.' : 'Sign in to keep your family calendar safely in sync.'}</p><div class="section-panel auth-panel"><label class="field-label" for="auth-email">Email</label><input class="text-input" id="auth-email" type="email" autocomplete="email"><label class="field-label" for="auth-password">Password</label><input class="text-input" id="auth-password" type="password" autocomplete="current-password"><p class="auth-error" id="auth-error">${escapeHtml(message)}</p><button class="primary-button" id="auth-submit">${signUp ? 'Create account' : 'Log in'}</button><button class="text-button auth-create" id="auth-toggle">${signUp ? 'Back to login' : 'Create an account'}</button></div></section>`; document.querySelector('#auth-submit').addEventListener('click', () => authenticate(signUp)); document.querySelector('#auth-toggle').addEventListener('click', () => { authMode = signUp ? 'login' : 'signup'; renderAuth(); }); }
async function authenticate(signUp) { const email = document.querySelector('#auth-email').value.trim(); const password = document.querySelector('#auth-password').value; const validEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email); if (!validEmail) return document.querySelector('#auth-error').textContent = 'Enter a valid email address.'; if (password.length < 6) return document.querySelector('#auth-error').textContent = 'Password must be at least 6 characters.'; const result = signUp ? await supabaseClient.auth.signUp({ email, password }) : await supabaseClient.auth.signInWithPassword({ email, password }); if (result.error) { console.error(result.error); const errorText = result.error.message || ''; if (/invalid api key/i.test(errorText)) return document.querySelector('#auth-error').textContent = 'The Supabase key is invalid. Copy the publishable key again in Project Settings → API Keys.'; if (/email not confirmed/i.test(errorText)) return document.querySelector('#auth-error').textContent = 'Please click the confirmation link in your email, then try logging in again.'; if (/already registered/i.test(errorText)) return document.querySelector('#auth-error').textContent = 'This email already has an account. Use Log in instead.'; return document.querySelector('#auth-error').textContent = signUp ? 'We could not create the account. Try again.' : 'We could not sign you in. Check your details and try again.'; } if (signUp && !result.data.session) { const confirmation = document.querySelector('#auth-error'); confirmation.textContent = 'Account created. Check your email, then log in.'; confirmation.classList.add('success'); } }
function renderFamilySetup(message = '') { document.querySelector('.bottom-nav').style.display = 'none'; app.innerHTML = `<section class="auth-view"><div class="auth-mark">🥛</div><p class="eyebrow">First-time setup</p><h1>Let's set up your family</h1><p class="subtitle">Create a new family or join one with an invite code.</p><div class="section-panel auth-panel"><label class="field-label" for="family-name">Family name</label><input class="text-input" id="family-name" placeholder="Kumar Family"><button class="primary-button" id="create-family">Create family</button><div class="setup-divider">or join an existing family</div><label class="field-label" for="family-code">Family invite code</label><input class="text-input" id="family-code" placeholder="KUMAR-7284" autocapitalize="characters"><button class="primary-button" id="join-family" style="background:#e8f1ee;color:var(--teal)">Join family</button><p class="auth-error" id="setup-error">${escapeHtml(message)}</p></div></section>`; document.querySelector('#create-family').addEventListener('click', createFamily); document.querySelector('#join-family').addEventListener('click', joinFamily); }
async function createFamily() { const name = document.querySelector('#family-name').value.trim(); if (!name) return document.querySelector('#setup-error').textContent = 'Enter a family name.'; const { data: family, error } = await supabaseClient.from('families').insert({ name, created_by: cloudUser.id }).select().single(); if (error) return cloudError(error); const membership = await supabaseClient.from('family_members').insert({ family_id: family.id, user_id: cloudUser.id, role: 'admin' }); if (membership.error) return cloudError(membership.error); await supabaseClient.from('family_settings').insert({ family_id: family.id, default_price: settings.price, quick_quantities: settings.quantities }); await enterCloud(cloudUser); }
async function joinFamily() { const code = document.querySelector('#family-code').value.trim().toUpperCase(); if (!code) return document.querySelector('#setup-error').textContent = 'Enter a family invite code.'; const { data, error } = await supabaseClient.rpc('join_family_by_code', { requested_code: code }); if (error || !data) return document.querySelector('#setup-error').textContent = 'That family code was not found.'; await enterCloud(cloudUser); }
async function enterCloud(user) { cloudUser = user; const { data, error } = await supabaseClient.from('family_members').select('family_id, role, families(id, name, invite_code)').eq('user_id', user.id).limit(1).maybeSingle(); if (error) return cloudError(error); if (!data) return renderFamilySetup(); activeFamily = { ...data.families, role: data.role }; document.querySelector('.bottom-nav').style.display = ''; document.querySelector('#settings-button').style.display = ''; try { await cloudPull(); render(); } catch (pullError) { cloudError(pullError); render(); } }
async function saveFamilySettings() { const price = Number(document.querySelector('#family-price').value); if (!Number.isFinite(price) || price < 0) return showToast('Enter a valid milk price.'); settings.price = price; saveData(); const { error } = await supabaseClient.from('family_settings').upsert({ family_id: activeFamily.id, default_price: price, quick_quantities: settings.quantities, updated_at: new Date().toISOString() }); if (error) return cloudError(error); setSyncStatus('☁ Synced'); showToast('Family milk price saved.'); }
function renderFamilySettings() { document.querySelector('.bottom-nav').style.display = 'none'; app.innerHTML = `<section><p class="eyebrow">Family settings</p><h1>${escapeHtml(activeFamily.name)}</h1><p class="subtitle">Signed in as ${escapeHtml(cloudUser.email || 'family member')} · ${escapeHtml(activeFamily.role)}</p><div class="section-panel"><h3>Milk price for this family</h3><div class="price-input"><span class="unit">₹</span><input class="text-input" id="family-price" type="number" min="0" step="0.01" value="${settings.price}"><span class="unit">/ L</span></div><button class="primary-button" id="save-family-settings">Save family price</button><h3>Family invite code</h3><p class="invite-code">${escapeHtml(activeFamily.invite_code)}</p><button class="primary-button" id="copy-invite">Copy invite code</button><button class="primary-button" id="backup-data" style="background:#e8f1ee;color:var(--teal)">Backup data</button><label class="primary-button" for="restore-data" style="display:block;text-align:center;background:#e8f1ee;color:var(--teal)">Restore local backup</label><input id="restore-data" type="file" accept="application/json" hidden><button class="text-button settings-back" id="back-to-today">← Back to today</button><button class="text-button logout-button" id="logout-button">Log out</button></div></section>`; document.querySelector('#save-family-settings').addEventListener('click', saveFamilySettings); document.querySelector('#copy-invite').addEventListener('click', async () => { await navigator.clipboard?.writeText(activeFamily.invite_code); showToast('Invite code copied.'); }); document.querySelector('#backup-data').addEventListener('click', backupData); document.querySelector('#restore-data').addEventListener('change', restoreBackup); document.querySelector('#back-to-today').addEventListener('click', () => { currentView = 'today'; document.querySelector('.bottom-nav').style.display = ''; render(); }); document.querySelector('#logout-button').addEventListener('click', () => supabaseClient.auth.signOut()); }
function backupData() { const payload = { version: 1, exportedAt: new Date().toISOString(), settings, records }; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); link.download = `milk-tracker-backup-${dateKey(today)}.json`; link.click(); URL.revokeObjectURL(link.href); showToast('Backup downloaded.'); }
function restoreBackup(event) { const file = event.target.files[0]; if (!file) return; if (!confirm('Restore backup? This replaces only this device\'s local cache. Cloud records are not overwritten.')) return; const reader = new FileReader(); reader.onload = () => { try { const payload = JSON.parse(reader.result); if (!payload.records || !payload.settings) throw new Error('Invalid backup'); records = payload.records; settings = payload.settings; saveData(); render(); showToast('Local backup restored.'); } catch (error) { console.error(error); showToast('Backup could not be restored.'); } }; reader.readAsText(file); }
async function boot() { if (!cloudConfigured || !window.supabase) { setSyncStatus('Local'); render(); return; } setSyncStatus('☁ Ready'); supabaseClient = window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.publishableKey); const { data } = await supabaseClient.auth.getSession(); if (data.session) await enterCloud(data.session.user); else renderAuth(); supabaseClient.auth.onAuthStateChange((event, session) => { if (event === 'SIGNED_IN' && session) enterCloud(session.user); if (event === 'SIGNED_OUT') { cloudUser = null; activeFamily = null; setSyncStatus('☁ Ready'); renderAuth(); } }); }

function saveData() {
  localStorage.setItem('milk-settings', JSON.stringify(settings));
  localStorage.setItem('milk-records', JSON.stringify(records));
}
function showToast(message, action) { const toast = document.querySelector('#toast'); toast.innerHTML = action ? `${message} <button class="toast-undo">Undo</button>` : message; toast.classList.add('show'); clearTimeout(toastTimer); undoAction = action; toast.querySelector('.toast-undo')?.addEventListener('click', () => { undoAction?.(); undoAction = null; toast.classList.remove('show'); }); toastTimer = setTimeout(() => { undoAction = null; toast.classList.remove('show'); }, 2600); }
function monthRecords(date) { const prefix = monthKey(date); return Object.entries(records).filter(([key]) => key.startsWith(prefix)).map(([key, value]) => ({ key, ...value })); }
function statsForMonth(date) { const items = monthRecords(date); const total = items.reduce((sum, item) => sum + item.quantity, 0); const days = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); const prices = items.map(item => item.price).filter(Number.isFinite); const price = prices.length ? prices[prices.length - 1] : settings.price; return { items, total, count: items.length, days, average: items.length ? total / items.length : 0, cost: items.reduce((sum, item) => sum + item.quantity * item.price, 0), averageCost: items.length ? items.reduce((sum, item) => sum + item.quantity * item.price, 0) / items.length : 0, highest: items.length ? Math.max(...items.map(item => item.quantity)) : 0, lowest: items.length ? Math.min(...items.map(item => item.quantity)) : 0, missing: days - items.length, price }; }
function formatMonth(date) { return monthFormatter.format(date); }
function render() { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === currentView)); if (currentView === 'today') renderToday(); if (currentView === 'calendar') renderCalendar(); if (currentView === 'history') { renderHistory(); renderYearSummary(); } }
function quantityButtons() { const quantities = [...new Set([...settings.quantities, 0.25, 0.75, 2.25, 3])].sort((a, b) => a - b); return quantities.map(quantity => `<button class="quantity-button" data-quantity="${quantity}">${quantity} L</button>`).join('') + '<button class="quantity-button other" data-other>Other</button>'; }
function renderToday() { const key = dateKey(today); const record = records[key]; const stats = statsForMonth(today); app.innerHTML = `<section class="today-view"><p class="eyebrow">${dateFormatter.format(today)}</p><h1>How much milk<br>did we get today?</h1><p class="subtitle">Tap a quantity. It saves automatically.</p><div class="entry-panel"><div class="entry-label">Today's quantity</div><div class="quantity-grid">${quantityButtons()}</div><div id="custom-entry"></div>${record ? `<div class="saved-banner"><span>✓ Saved: ${litres(record.quantity)}</span><button class="text-button" data-edit-today>Edit</button></div>` : '<div class="saved-banner" style="background:#fff8e4;color:#755b21">Milk not recorded yet</div>'}<div class="note-row"><label for="today-note">Optional note</label><input class="text-input" id="today-note" placeholder="Add a note for today" value="${escapeHtml(record?.note || '')}"></div></div><div class="summary-panel"><div class="summary-heading"><h2>${formatMonth(today)}</h2><span class="month-total">${litres(stats.total)}</span></div><div class="stat"><span class="stat-label">Days recorded</span><span class="stat-value">${stats.count} / ${stats.days}</span></div><div class="stat"><span class="stat-label">Estimated cost</span><span class="stat-value">${money(stats.cost)}</span></div><button class="primary-button" data-view-calendar>View calendar</button><button class="primary-button" data-view-history style="background:#e8f1ee;color:var(--teal)">View history</button></div></section>`; bindToday(); }
function bindToday() { const todayKey = dateKey(today); app.querySelectorAll('[data-quantity]').forEach(button => button.addEventListener('click', () => saveRecord(keyFor(selectedDate = today), Number(button.dataset.quantity)))); app.querySelector('[data-other]').addEventListener('click', () => { document.querySelector('#custom-entry').innerHTML = `<div class="custom-entry"><label class="field-label" for="custom-quantity">Enter quantity</label><div class="inline-form"><input class="text-input" id="custom-quantity" type="number" min="0.01" max="100" step="0.01" placeholder="e.g. 1.35"><span class="unit">L</span></div><button class="primary-button" id="save-custom">Save</button></div>`; document.querySelector('#custom-quantity').focus(); document.querySelector('#save-custom').addEventListener('click', () => { const value = Number(document.querySelector('#custom-quantity').value); if (!value || value <= 0 || value > 100) return showToast('Enter a quantity between 0.01 and 100 L.'); saveRecord(dateKey(today), value); }); }); app.querySelector('[data-edit-today]')?.addEventListener('click', () => document.querySelector('.quantity-grid').scrollIntoView({ behavior: 'smooth', block: 'center' })); app.querySelector('#today-note').addEventListener('change', (event) => { if (records[todayKey]) { records[todayKey].note = event.target.value.trim(); saveData(); showToast('Note saved.'); } }); app.querySelector('[data-view-calendar]')?.addEventListener('click', () => { currentView = 'calendar'; render(); }); app.querySelector('[data-view-history]')?.addEventListener('click', () => { currentView = 'history'; render(); }); }
function keyFor(date) { return dateKey(date); }
function saveRecord(key, quantity) { if (isFutureKey(key)) return showToast('Future dates cannot be recorded.'); const previous = records[key] ? { ...records[key] } : null; records[key] = { quantity, price: records[key]?.price ?? settings.price, note: records[key]?.note || '', updatedAt: new Date().toISOString() }; saveData(); if (cloudReady()) cloudSaveRecord(key).catch(error => { cloudError(error); queueSync(key); }); showToast(`Saved ${litres(quantity)}`, () => { if (previous) records[key] = previous; else delete records[key]; saveData(); if (cloudReady()) { if (previous) cloudSaveRecord(key).catch(error => { cloudError(error); queueSync(key, !previous); }); else cloudDeleteRecord(key).catch(error => { cloudError(error); queueSync(key, true); }); } render(); }); render(); }
function renderCalendar() { const stats = statsForMonth(visibleMonth); const firstDay = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth(), 1); const startOffset = (firstDay.getDay() + 6) % 7; const days = Array.from({ length: stats.days }, (_, index) => index + 1); const cells = [...Array(startOffset).fill(null), ...days]; while (cells.length % 7) cells.push(null); app.innerHTML = `<section><div class="page-head"><div><p class="eyebrow">Your milk calendar</p><h1>${formatMonth(visibleMonth)}</h1></div><div class="month-switcher"><button data-month="previous" aria-label="Previous month">‹</button><span class="month-name">${formatMonth(visibleMonth).split(' ')[0]}</span><button data-month="next" aria-label="Next month">›</button></div></div><div class="calendar-wrap"><div class="weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="calendar-grid">${cells.map(day => day ? dayCell(day, visibleMonth) : '<div class="day empty"></div>').join('')}</div></div><div class="legend"><span><i class="dot"></i> Recorded</span><span><i class="dot empty"></i> Not recorded</span><span><i class="dot today"></i> Today</span></div><div class="summary-panel"><div class="summary-heading"><h2>${formatMonth(visibleMonth)} summary</h2><span class="month-total">${litres(stats.total)}</span></div><div class="stat"><span class="stat-label">Days recorded</span><span class="stat-value">${stats.count} / ${stats.days}</span></div><div class="stat"><span class="stat-label">Missing days</span><span class="stat-value">${stats.missing}</span></div><div class="stat"><span class="stat-label">Average per day</span><span class="stat-value">${litres(stats.average || 0)}</span></div><div class="stat"><span class="stat-label">Total cost</span><span class="stat-value">${money(stats.cost)}</span></div><div class="stat"><span class="stat-label">Average daily cost</span><span class="stat-value">${money(stats.averageCost)}</span></div><div class="stat"><span class="stat-label">Highest / lowest</span><span class="stat-value">${stats.highest ? `${litres(stats.highest)} / ${litres(stats.lowest)}` : '—'}</span></div></div>${stats.missing ? `<div class="report-strip"><div><strong>⚠ ${stats.missing} ${stats.missing === 1 ? 'day is' : 'days are'} missing</strong><span>Tap any date to add its quantity.</span></div></div>` : `<div class="report-strip"><div><strong>✓ Every day is recorded</strong><span>Lovely work keeping the calendar up to date.</span></div></div>`}</section>`; bindCalendar(); }
function dayCell(day, month) { const date = new Date(month.getFullYear(), month.getMonth(), day); const key = dateKey(date); const record = records[key]; const future = isFutureKey(key); return `<button class="day ${record ? '' : 'not-recorded'} ${sameDay(date, today) ? 'today' : ''} ${future ? 'future' : ''}" data-date="${key}" ${future ? 'disabled title="Future dates cannot be recorded."' : ''}><span class="day-number">${day}</span><span class="day-quantity">${record ? litres(record.quantity) : '—'}</span></button>`; }
function bindCalendar() { app.querySelectorAll('[data-date]:not([disabled])').forEach(button => button.addEventListener('click', () => openDateEditor(button.dataset.date))); app.querySelector('[data-month="previous"]').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() - 1, 1); renderCalendar(); }); app.querySelector('[data-month="next"]').addEventListener('click', () => { visibleMonth = new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 1); renderCalendar(); }); const todayButton = document.createElement('button'); todayButton.className = 'today-link'; todayButton.textContent = 'Today'; todayButton.addEventListener('click', () => { visibleMonth = new Date(today.getFullYear(), today.getMonth(), 1); renderCalendar(); }); app.querySelector('.month-switcher').append(todayButton); const labels = [...app.querySelectorAll('.summary-panel .stat-label')]; if (labels[2]) labels[2].textContent = 'Average on recorded days'; const calendarAverage = document.createElement('div'); calendarAverage.className = 'stat'; calendarAverage.innerHTML = `<span class="stat-label">Average per calendar day</span><span class="stat-value">${litres(statsForMonth(visibleMonth).total / statsForMonth(visibleMonth).days || 0)}</span>`; app.querySelector('.summary-panel').insertBefore(calendarAverage, app.querySelector('.summary-panel').children[4]); renderChart(); }
function renderChart() { const stats = statsForMonth(visibleMonth); const chart = document.createElement('div'); chart.className = 'chart-panel'; chart.innerHTML = '<h3>Daily milk</h3><div class="bar-chart"></div>'; const bars = chart.querySelector('.bar-chart'); const max = Math.max(...stats.items.map(item => item.quantity), 1); stats.items.sort((a, b) => a.key.localeCompare(b.key)).forEach(item => { const bar = document.createElement('div'); bar.className = 'chart-bar'; bar.style.height = `${Math.max(8, item.quantity / max * 100)}%`; bar.title = `${item.key}: ${litres(item.quantity)}`; bars.append(bar); }); app.querySelector('section').append(chart); }
function openDateEditor(key) { if (isFutureKey(key)) return showToast('Future dates cannot be recorded.'); const date = parseDate(key); const existing = records[key]; app.innerHTML = `<section><div class="page-head"><div><p class="eyebrow">Calendar entry</p><h1>${dateFormatter.format(date)}</h1></div><button class="text-button" data-back-calendar>← Calendar</button></div><div class="entry-panel"><div class="entry-label">Choose quantity received</div><div class="quantity-grid">${quantityButtons()}</div><div class="custom-entry"><label class="field-label" for="edit-quantity">Or enter another amount</label><div class="inline-form"><input class="text-input" id="edit-quantity" type="number" min="0.01" max="100" step="0.01" placeholder="e.g. 1.35" value="${existing?.quantity || ''}"><span class="unit">L</span></div><button class="primary-button" id="save-date-custom">Save quantity</button></div><div class="note-row"><label for="edit-note">Optional note</label><input class="text-input" id="edit-note" placeholder="Anything worth remembering?" value="${escapeHtml(existing?.note || '')}"></div>${existing ? '<button class="danger-button" id="delete-entry">Delete entry</button>' : ''}</div></section>`; app.querySelectorAll('[data-quantity]').forEach(button => button.addEventListener('click', () => { saveRecord(key, Number(button.dataset.quantity)); openDateEditor(key); })); app.querySelector('#save-date-custom').addEventListener('click', () => { const value = Number(app.querySelector('#edit-quantity').value); if (!value || value <= 0 || value > 100) return showToast('Enter a quantity between 0.01 and 100 L.'); saveRecord(key, value); openDateEditor(key); }); app.querySelector('#edit-note').addEventListener('change', event => { if (records[key]) { records[key].note = event.target.value.trim(); saveData(); if (cloudReady()) cloudSaveRecord(key).catch(cloudError); showToast('Note saved.'); } }); app.querySelector('#delete-entry')?.addEventListener('click', () => { if (!confirm(`Delete milk record for ${dateFormatter.format(date)}?`)) return; delete records[key]; saveData(); if (cloudReady()) cloudDeleteRecord(key).catch(cloudError); renderCalendar(); showToast('Entry deleted.'); }); app.querySelector('[data-back-calendar]').addEventListener('click', () => renderCalendar()); }
function renderHistory() { const months = [...new Set(Object.keys(records).map(key => key.slice(0, 7)))].sort().reverse(); app.innerHTML = `<section><p class="eyebrow">Your family archive</p><h1>History</h1><p class="subtitle">A quick look at all completed months.</p><div class="section-panel"><div class="history-list">${months.length ? months.map(key => { const stats = statsForMonth(parseDate(`${key}-01`)); return `<div class="history-row"><button data-history-month="${key}"><span class="history-month">${formatMonth(parseDate(`${key}-01`))}</span><span class="history-meta">${stats.count} days recorded · ${money(stats.cost)}</span></button><span class="history-total">${litres(stats.total)}</span></div>`; }).join('') : '<div class="empty-state">Your past months will appear here after you start recording milk.</div>'}</div></div></section>`; app.querySelectorAll('[data-history-month]').forEach(button => button.addEventListener('click', () => { visibleMonth = parseDate(`${button.dataset.historyMonth}-01`); currentView = 'calendar'; render(); })); }
function renderYearSummary() { const year = today.getFullYear(); const items = Object.entries(records).filter(([key]) => key.startsWith(`${year}-`)); const total = items.reduce((sum, [, record]) => sum + record.quantity, 0); const cost = items.reduce((sum, [, record]) => sum + record.quantity * record.price, 0); const months = new Set(items.map(([key]) => key.slice(0, 7))).size; const panel = document.createElement('div'); panel.className = 'summary-panel yearly-summary'; panel.innerHTML = `<div class="summary-heading"><h2>${year} summary</h2><span class="month-total">${litres(total)}</span></div><div class="stat"><span class="stat-label">Total cost</span><span class="stat-value">${money(cost)}</span></div><div class="stat"><span class="stat-label">Average / recorded day</span><span class="stat-value">${litres(items.length ? total / items.length : 0)}</span></div><div class="stat"><span class="stat-label">Months recorded</span><span class="stat-value">${months} / 12</span></div>`; app.querySelector('section').append(panel); }
function addLocalBackupControls() { const exportButton = document.querySelector('#export-data'); if (!exportButton || document.querySelector('#backup-data')) return; exportButton.insertAdjacentHTML('afterend', '<button class="primary-button" id="backup-data" style="background:#e8f1ee;color:var(--teal)">Backup data</button><label class="primary-button" for="restore-data" style="display:block;text-align:center;background:#e8f1ee;color:var(--teal)">Restore backup</label><input id="restore-data" type="file" accept="application/json" hidden>'); document.querySelector('#backup-data').addEventListener('click', backupData); document.querySelector('#restore-data').addEventListener('change', restoreBackup); }
window.addEventListener('offline', () => setSyncStatus('⚠ Offline', true));
window.addEventListener('online', () => { if (cloudReady()) flushPending().then(() => cloudPull()).then(render).catch(cloudError); else setSyncStatus('Local'); });
function renderSettings() { app.innerHTML = `<section><p class="eyebrow">Keep it simple</p><h1>Settings</h1><p class="subtitle">Your price is saved on each entry, so old totals stay accurate.</p><div class="section-panel"><div class="settings-form"><div><label class="field-label" for="milk-price">Milk price per litre</label><div class="price-input"><span class="unit">₹</span><input class="text-input" id="milk-price" type="number" min="0" step="0.01" value="${settings.price}"><span class="unit">/ L</span></div></div><div><span class="field-label">Quick quantities</span><div class="settings-quantities">${settings.quantities.map((quantity, index) => `<span class="quantity-chip">${quantity} L <button data-remove-quantity="${index}" aria-label="Remove ${quantity} litres">×</button></span>`).join('')}</div><div class="add-quantity"><input class="text-input" id="new-quantity" type="number" min="0.01" max="100" step="0.01" placeholder="Add quantity"><button class="primary-button" id="add-quantity" style="width:auto;margin-top:0;padding:0 16px">Add</button></div></div><button class="primary-button" id="save-settings">Save settings</button><button class="primary-button" id="export-data" style="background:#e8f1ee;color:var(--teal)">Export data as CSV</button></div></div></section>`; app.querySelectorAll('[data-remove-quantity]').forEach(button => button.addEventListener('click', () => { settings.quantities.splice(Number(button.dataset.removeQuantity), 1); saveData(); renderSettings(); addLocalBackupControls(); })); app.querySelector('#add-quantity').addEventListener('click', () => { const value = Number(app.querySelector('#new-quantity').value); if (!value || value <= 0) return; settings.quantities.push(value); settings.quantities = [...new Set(settings.quantities)].sort((a, b) => a - b); saveData(); renderSettings(); addLocalBackupControls(); }); app.querySelector('#save-settings').addEventListener('click', () => { const price = Number(app.querySelector('#milk-price').value); if (price < 0 || !Number.isFinite(price)) return showToast('Enter a valid milk price.'); settings.price = price; saveData(); showToast('Settings saved.'); }); app.querySelector('#export-data').addEventListener('click', exportCsv); addLocalBackupControls(); }
function exportCsv() { const rows = [['Date', 'Quantity (L)', 'Price per litre (INR)', 'Total cost (INR)', 'Note']].concat(Object.entries(records).sort().map(([key, record]) => [key, record.quantity, record.price, (record.quantity * record.price).toFixed(2), record.note || ''])); const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'daily-milk-tracker.csv'; link.click(); URL.revokeObjectURL(link.href); showToast('CSV export downloaded.'); }

document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => { currentView = item.dataset.view; render(); }));
document.querySelector('#settings-button').addEventListener('click', () => { if (!cloudReady()) { currentView = 'settings'; document.querySelectorAll('.nav-item').forEach(item => item.classList.remove('active')); renderSettings(); return; } renderFamilySettings(); });
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('sw.js'));
boot();
